FactorioItemBrowser\PortalApi\Server\Transfer\SettingMetaData:
  exclusion_policy: all
  properties:
    combinationId:
      type: string
    name:
      type: string
    status:
      type: string
    isTemporary:
      type: boolean
