FactorioItemBrowser\PortalApi\Server\Transfer\SettingData:
  exclusion_policy: all
  properties:
    combinationId:
      type: string
    combinationHash:
      type: string
    name:
      type: string
    locale:
      type: string
    recipeMode:
      type: string
    status:
      type: string
    isTemporary:
      type: boolean
