FactorioItemBrowser\PortalApi\Server\Transfer\SettingStatusData:
  access_type: public_method
  exclusion_policy: all
  properties:
    status:
      type: string
    exportTime:
      type: DateTime<'Y-m-d\TH:i:s.vP'>
    existingSetting:
      type: FactorioItemBrowser\PortalApi\Server\Transfer\SettingDetailsData
