FactorioItemBrowser\PortalApi\Server\Transfer\RecipeData:
  exclusion_policy: all
  properties:
    craftingTime:
      type: float
    ingredients:
      type: array<FactorioItemBrowser\PortalApi\Server\Transfer\RecipeItemData>
    products:
      type: array<FactorioItemBrowser\PortalApi\Server\Transfer\RecipeItemData>
    isExpensive:
      type: bool
