FactorioItemBrowser\PortalApi\Server\Transfer\RecipeItemData:
  exclusion_policy: all
  properties:
    type:
      type: string
    name:
      type: string
    label:
      type: string
    amount:
      type: float
