FactorioItemBrowser\PortalApi\Server\Transfer\InitData:
  exclusion_policy: all
  properties:
    setting:
      type: FactorioItemBrowser\PortalApi\Server\Transfer\SettingMetaData
    lastUsedSetting:
      type: FactorioItemBrowser\PortalApi\Server\Transfer\SettingMetaData
    locale:
      type: string
    sidebarEntities:
      type: array<FactorioItemBrowser\PortalApi\Server\Transfer\SidebarEntityData>
    scriptVersion:
      type: string
