FactorioItemBrowser\PortalApi\Server\Transfer\SessionInitData:
  access_type: public_method
  exclusion_policy: all
  properties:
    setting:
      type: FactorioItemBrowser\PortalApi\Server\Transfer\SettingMetaData
    settingHash:
      type: string
    locale:
      type: string
    sidebarEntities:
      type: array<FactorioItemBrowser\PortalApi\Server\Transfer\SidebarEntityData>
    scriptVersion:
      type: string
