FactorioItemBrowser\PortalApi\Server\Transfer\ItemListData:
  access_type: public_method
  exclusion_policy: all
  properties:
    results:
      type: array<FactorioItemBrowser\PortalApi\Server\Transfer\ItemMetaData>
    numberOfResults:
      type: int
