FactorioItemBrowser\PortalApi\Server\Transfer\RecipeMachinesData:
  exclusion_policy: all
  properties:
    results:
      type: array<FactorioItemBrowser\PortalApi\Server\Transfer\MachineData>
    numberOfResults:
      type: int
