FactorioItemBrowser\PortalApi\Server\Transfer\ModData:
  exclusion_policy: all
  properties:
    name:
      type: string
    label:
      type: string
    author:
      type: string
    version:
      type: string
