FactorioItemBrowser\PortalApi\Server\Transfer\ItemRecipesData:
  exclusion_policy: all
  properties:
    type:
      type: string
    name:
      type: string
    label:
      type: string
    description:
      type: string
    results:
      type: array<FactorioItemBrowser\PortalApi\Server\Transfer\EntityData>
    numberOfResults:
      type: int
