FactorioItemBrowser\PortalApi\Server\Transfer\RecipeDetailsData:
  exclusion_policy: all
  properties:
    name:
      type: string
    label:
      type: string
    description:
      type: string
    recipe:
      type: FactorioItemBrowser\PortalApi\Server\Transfer\RecipeData
    expensiveRecipe:
      type: FactorioItemBrowser\PortalApi\Server\Transfer\RecipeData
