openapi: "3.0.0"
info:
  version: 1.0.0
  title: Factorio Item Browser - Portal API
  contact:
    name: BluePsyduck
    email: bluepsyduck@gmx.com
  description: The API used by the portal frontend to receive any data from the backend.

tags:
  - name: Item
    description: Requests related to item details.
  - name: Search
    description: Requests related with searching for items, recipes etc.
  - name: Style
    description: Requests related to additional styles provided by the server.

paths:
  /{type}/{name}/ingredients:
    get:
      summary: Returns the recipes where the requested item is an ingredient of.
      operationId: item.ingredients
      tags:
        - Item
      parameters:
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/indexOfFirstResult"
        - $ref: "#/components/parameters/numberOfResults"
      responses:
        200:
          description: The list of matched recipes.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemRecipesData"
  /{type}/{name}/products:
    get:
      summary: Returns the recipes where the requested item is a product of.
      operationId: item.products
      tags:
        - Item
      parameters:
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/indexOfFirstResult"
        - $ref: "#/components/parameters/numberOfResults"
      responses:
        200:
          description: The list of matched recipes.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemRecipesData"

  /search:
    get:
      summary: Searches for entities matching a query.
      operationId: search
      tags:
        - Search
      parameters:
        - $ref: "#/components/parameters/query"
        - $ref: "#/components/parameters/indexOfFirstResult"
        - $ref: "#/components/parameters/numberOfResults"
      responses:
        200:
          description: The list of entities matching the query.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResultData"

  /style/icons:
    post:
      summary: Returns the icons as stylesheet.
      operationId: style.icons
      tags:
        - Style
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NamesByTypes"
        required: true
      responses:
        200:
          description: The stylesheet for the requested icons.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IconsStyleData"

components:
  parameters:
    type:
      name: type
      in: path
      description: The type of the item or fluid.
      required: true
      schema:
        type: string
        enum:
          - item
          - fluid
        example: item
    name:
      name: name
      in: path
      description: The name of the item or fluid.
      required: true
      schema:
        type: string
        example: copper-wire

    indexOfFirstResult:
      name: indexOfFirstResult
      in: query
      description: The index of the first result to return, starting at 0.
      required: true
      schema:
        type: integer
        example: "0"
    numberOfResults:
      name: numberOfResults
      in: query
      description: The number of results to return.
      required: true
      schema:
        type: integer
        example: 24
    query:
      name: query
      in: query
      description: The query to use for the search.
      required: true
      schema:
        type: string
        example: iron plate

  schemas:
    EntityData:
      type: object
      properties:
        type:
          type: string
          description: The type of the entity.
          example: item
        name:
          type: string
          description: The internal name of the entity.
          example: electronic-circuit
        label:
          type: string
          description: The translated label of the entity.
          example: Elektronischer Schaltkreis
        recipes:
          type: array
          items:
            $ref: "#/components/schemas/RecipeData"
        numberOfRecipes:
          type: integer
          description: The total number of recipes available for the entity.
          example: 42

    IconsStyleData:
      type: object
      properties:
        processedEntities:
          $ref: "#/components/schemas/NamesByTypes"
        style:
          type: string
          description: The style representing the icons of the requested entities.
          example: ".example-style { background: red; }"

    ItemRecipesData:
      type: object
      properties:
        type:
          type: string
          enum:
            - item
            - fluid
          description: The type of the requested item or fluid.
          example: item
        name:
          type: string
          description: The name of the requested item or fluid.
          example: copper-wire
        label:
          type: string
          description: The translated label of the requested item or fluid.
          example: Kupferkabel
        description:
          type: string
          description: The translated description of the requested item or fluid.
          example: Kann mit Linke Maustaste zum Verbinden und Trennen von Strommasten und Stromschaltern verwendet werden.
        results:
          type: array
          description: The recipes related to the requested item.
          items:
            $ref: "#/components/schemas/EntityData"
        numberOfResults:
          type: integer
          description: The total number of recipes available for the item.
          example: 42

    NamesByTypes:
      type: object
      description: The names of entities grouped by their type.
      additionalProperties:
        type: array
        items:
          type: string
      example:
        item: ["iron-plate", "steel-plate"]
        fluid: ["heavy-oil"]

    RecipeData:
      type: object
      properties:
        craftingTime:
          type: number
          description: The crafting time of the recipe in seconds.
          example: 13.37
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/RecipeItemData"
          description: The ingredients of the recipe.
        products:
          type: array
          items:
            $ref: "#/components/schemas/RecipeItemData"
          description: The products of the recipe.
        isExpensive:
          type: boolean
          description: Whether the recipe is used in the expensive mode.
          example: false

    RecipeItemData:
      type: object
      properties:
        type:
          type: string
          enum:
            - item
            - recipe
          description: The type of the item.
          example: item
        name:
          type: string
          description: The internal name of the item.
          example: iron-plate
        label:
          type: string
          description: The translated label of the item.
          example: Eisenplatte
        amount:
          type: number
          description: The amount of the item in the recipe.
          example: 42

    SearchResultData:
      type: object
      properties:
        query:
          type: string
          description: The query used for the search.
          example: iron
        results:
          type: array
          items:
            $ref: "#/components/schemas/EntityData"
          description: The actual search results.
        numberOfResults:
          type: integer
          description: The total number of search results.
          example: 42

