openapi: "3.0.0"
info:
  version: 1.0.0
  title: Factorio Item Browser - Portal API
  contact:
    name: BluePsyduck
    email: bluepsyduck@gmx.com
  description: The API used by the portal frontend to receive any data from the backend.

tags:
  - name: Item
    description: Requests related to item details.
  - name: Recipe
    description: Requests related to recipe details.
  - name: Search
    description: Requests related with searching for items, recipes etc.
  - name: Session
    description: Requests related to the session handling.
  - name: Sidebar
    description: Requests related to the sidebar of the browser.
  - name: Style
    description: Requests related to additional styles provided by the server.

paths:
  /{type}/{name}/ingredients:
    get:
      summary: Returns the recipes where the requested item is an ingredient of.
      operationId: item.ingredients
      tags:
        - Item
      parameters:
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/indexOfFirstResult"
        - $ref: "#/components/parameters/numberOfResults"
      responses:
        200:
          description: The list of matched recipes.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemRecipesData"
  /{type}/{name}/products:
    get:
      summary: Returns the recipes where the requested item is a product of.
      operationId: item.products
      tags:
        - Item
      parameters:
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/indexOfFirstResult"
        - $ref: "#/components/parameters/numberOfResults"
      responses:
        200:
          description: The list of matched recipes.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemRecipesData"

  /recipe/{name}:
    get:
      summary: Returns the detauls of the recipe.
      operationId: recipe.details
      tags:
        - Recipe
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        200:
          description: The recipe details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeDetailsData"

  /recipe/{name}/machines:
    get:
      summary: Returns a list of machines able to craft the specified recipe.
      operationId: recipe.machines
      tags:
        - Recipe
      parameters:
        - $ref: "#/components/parameters/name"
        - $ref: "#/components/parameters/indexOfFirstResult"
        - $ref: "#/components/parameters/numberOfResults"
      responses:
        200:
          description: The list of machines.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecipeMachinesData"

  /search:
    get:
      summary: Searches for entities matching a query.
      operationId: search
      tags:
        - Search
      parameters:
        - $ref: "#/components/parameters/query"
        - $ref: "#/components/parameters/indexOfFirstResult"
        - $ref: "#/components/parameters/numberOfResults"
      responses:
        200:
          description: The list of entities matching the query.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResultData"

  /session/init:
    get:
      summary: Initializes the session.
      operationId: session.init
      tags:
        - Session
      responses:
        200:
          description: The initial settings of the session.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionInitData"

  /sidebar/entities:
    post:
      summary: Sends changes to the sidebar to the server.
      operationId: sidebar.entities
      tags:
        - Sidebar
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SidebarEntityData"
      responses:
        204:
          description: The chnages were successfully processed on the server.

  /style/icons:
    post:
      summary: Returns the icons as stylesheet.
      operationId: style.icons
      tags:
        - Style
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NamesByTypes"
        required: true
      responses:
        200:
          description: The stylesheet for the requested icons.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IconsStyleData"

components:
  parameters:
    type:
      name: type
      in: path
      description: The type of the item or fluid.
      required: true
      schema:
        type: string
        enum:
          - item
          - fluid
        example: item
    name:
      name: name
      in: path
      description: The name of the item, fluid or recipe.
      required: true
      schema:
        type: string
        example: copper-cable

    indexOfFirstResult:
      name: indexOfFirstResult
      in: query
      description: The index of the first result to return, starting at 0.
      required: true
      schema:
        type: integer
        example: "0"
    numberOfResults:
      name: numberOfResults
      in: query
      description: The number of results to return.
      required: true
      schema:
        type: integer
        example: 24
    query:
      name: query
      in: query
      description: The query to use for the search.
      required: true
      schema:
        type: string
        example: iron plate

  schemas:
    EntityData:
      type: object
      description: The data of an entity.
      properties:
        type:
          type: string
          description: The type of the entity.
          example: item
        name:
          type: string
          description: The internal name of the entity.
          example: electronic-circuit
        label:
          type: string
          description: The translated label of the entity.
          example: Elektronischer Schaltkreis
        recipes:
          type: array
          items:
            $ref: "#/components/schemas/RecipeData"
        numberOfRecipes:
          type: integer
          description: The total number of recipes available for the entity.
          example: 42

    IconsStyleData:
      type: object
      description: The data containing the generated style.
      properties:
        processedEntities:
          $ref: "#/components/schemas/NamesByTypes"
        style:
          type: string
          description: The style representing the icons of the requested entities.
          example: ".example-style { background: red; }"

    ItemRecipesData:
      type: object
      description: The data containing recipes with a certain item.
      properties:
        type:
          type: string
          enum:
            - item
            - fluid
          description: The type of the requested item or fluid.
          example: item
        name:
          type: string
          description: The name of the requested item or fluid.
          example: copper-cable
        label:
          type: string
          description: The translated label of the requested item or fluid.
          example: Kupferkabel
        description:
          type: string
          description: The translated description of the requested item or fluid.
          example: Kann mit Linke Maustaste zum Verbinden und Trennen von Strommasten und Stromschaltern verwendet werden.
        results:
          type: array
          description: The recipes related to the requested item.
          items:
            $ref: "#/components/schemas/EntityData"
        numberOfResults:
          type: integer
          description: The total number of recipes available for the item.
          example: 42

    MachineData:
      type: object
      description: The data of a machine.
      properties:
        name:
          type: string
          description: The name of the machine.
          example: assembling-machine-1
        label:
          type: string
          description: The translated label of the machine.
          example: Montagemaschine 1
        craftingSpeed:
          type: number
          description: The crafting speed of the machine.
          example: 13.37
        numberOfItems:
          type: number
          description: The number of items supported by the machine. 255 for unlimited.
          example: 42
        numberOfFluids:
          type: number
          description: The number of fluids supported by the machine.
          example: 21
        numberOfModules:
          type: number
          description: The number of module slots the machine has.
          example: 69
        energyUsage:
          type: number
          description: The energy usage of the machine.
          example: 1337
        energyUsageUnit:
          type: string
          enum:
            - W
            - kW
            - MW
            - GW
            - TW
            - PW
            - EW
            - ZW
            - YW
          description: The unit of the energyUsage value.
          example: kW

    NamesByTypes:
      type: object
      description: The names of entities grouped by their type.
      additionalProperties:
        type: array
        items:
          type: string
      example:
        item: ["iron-plate", "steel-plate"]
        fluid: ["heavy-oil"]

    RecipeData:
      type: object
      description: The data of a single recipe.
      properties:
        craftingTime:
          type: number
          description: The crafting time of the recipe in seconds.
          example: 13.37
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/RecipeItemData"
          description: The ingredients of the recipe.
        products:
          type: array
          items:
            $ref: "#/components/schemas/RecipeItemData"
          description: The products of the recipe.
        isExpensive:
          type: boolean
          description: Whether the recipe is used in the expensive mode.
          example: false

    RecipeDetailsData:
      type: object
      description: The data containing the details of a recipe.
      properties:
        name:
          type: string
          description: The name of the recipe.
          example: copper-cable
        label:
          type: string
          description: The translated label of the recipe.
        description:
          type: string
          description: The translated description of the recipe.
        recipe:
          $ref: "#/components/schemas/RecipeData"
        expensiveRecipe:
          $ref: "#/components/schemas/RecipeData"

    RecipeItemData:
      type: object
      description: The data of an item being part of a recipe.
      properties:
        type:
          type: string
          enum:
            - item
            - recipe
          description: The type of the item.
          example: item
        name:
          type: string
          description: The internal name of the item.
          example: iron-plate
        label:
          type: string
          description: The translated label of the item.
          example: Eisenplatte
        amount:
          type: number
          description: The amount of the item in the recipe.
          example: 42

    RecipeMachinesData:
      type: object
      description: The data containing the machines for a recipe.
      properties:
        results:
          type: array
          description: The machines able to craft the recipe.
          items:
            $ref: "#/components/schemas/MachineData"
        numberOfResults:
          type: integer
          description: The total number of machines.
          example: 42

    SearchResultData:
      type: object
      description: The data containing results of the search.
      properties:
        query:
          type: string
          description: The query used for the search.
          example: iron
        results:
          type: array
          items:
            $ref: "#/components/schemas/EntityData"
          description: The actual search results.
        numberOfResults:
          type: integer
          description: The total number of search results.
          example: 42

    SessionInitData:
      type: object
      description: The data to initialize the session.
      properties:
        sidebarEntities:
          type: array
          description: The sidebar entities of the session.
          items:
            $ref: "#/components/schemas/SidebarEntityData"

    SidebarEntityData:
      type: object
      description: The data representing an entity of the sidebar.
      properties:
        type:
          type: string
          enum:
            - item
            - fluid
            - recipe
          description: The type of the entity.
          example: item
        name:
          type: string
          description: The name of the entity.
          example: electronic-circuit
        label:
          type: string
          description: The translated label of the entity.
          example: Elektronischer Schaltkreis
        pinnedPosition:
          type: integer
          description: The position of the entity in the pinned list. 0 if not pinned.
          example: 7
        lastViewTime:
          type: string
          format: date-time
          description: The timestamp when the entity was last viewed.
          example: "2038-01-19T03:14:07.000Z"
